name: "Git AI PR Close"
description: "Track AI-assisted development on PR close and export OpenTelemetry data"
author: "acunniffe"
branding:
  icon: "git-pull-request"
  color: "purple"

inputs:
  github-token:
    description: "GitHub token for API access"
    required: false
    default: ${{ github.token }}
  pr-url:
    description: "Pull request URL"
    required: true
  repo-url:
    description: "Repository URL"
    required: false
    default: ${{ github.server_url }}/${{ github.repository }}
  merge-commit-sha:
    description: "Merge commit SHA"
    required: true
  OTEL_EXPORTER_OTLP_ENDPOINT:
    description: "OpenTelemetry endpoint URL"
    required: false
  OTEL_EXPORTER_OTLP_HEADERS:
    description: "OpenTelemetry headers (key=value format, comma separated)"
    required: false
  OTEL_SERVICE_NAME:
    description: "OpenTelemetry service name"
    required: false

runs:
  using: "composite"
  steps:
    # - name: Checkout repository
    #   uses: actions/checkout@v4
    #   with:
    #     path: git-ai-ci-clone
    #     fetch-depth: 0
    #     ref: ${{ inputs.merge-commit-sha }}

    - name: Install git-ai
      shell: bash
      run: |
        export GIT_AI_RELEASE_TAG="v1.0.23-next-7236db5"
        curl -fsSL https://raw.githubusercontent.com/acunniffe/git-ai/main/install.sh | bash
        echo "$HOME/.git-ai/bin" >> $GITHUB_PATH
        curl -fsSL https://git-ai-otel.s3.us-east-2.amazonaws.com/git-ai-otel-latest.tar.gz -o git-ai-otel.tar.gz
        tar -xzf git-ai-otel.tar.gz
        chmod +x git-ai-otel
        sudo mv git-ai-otel /usr/local/bin/

    - name: Configure git user
      shell: bash
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Run git-ai pr CI
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        OTEL_EXPORTER_OTLP_ENDPOINT: ${{ inputs.OTEL_EXPORTER_OTLP_ENDPOINT }}
        OTEL_EXPORTER_OTLP_HEADERS: ${{ inputs.OTEL_EXPORTER_OTLP_HEADERS }}
        OTEL_SERVICE_NAME: ${{ inputs.OTEL_SERVICE_NAME }}
      run: |
        export PATH="$HOME/.git-ai/bin:$PATH"
        git-ai ci github run --no-cleanup
        cd git-ai-ci-clone
        git fetch origin
        git-ai-otel export-pr "${{ inputs.pr-url }}" "${{ inputs.repo-url }}" merged "${{ inputs.merge-commit-sha }}"
